[AdditionalOptions]
extensions            = noControls.js|swapPlaybackTime.js
custom_apps           =
sidebar_config        = 0
home_config           = 1
experimental_features = 1

[Patch]

[Setting]
spotify_launch_flags   = 
check_spicetify_update = 1
spotify_path           = C:\Users\daani\AppData\Roaming\Spotify
prefs_path             = C:\Users\daani\AppData\Roaming\Spotify\prefs
inject_theme_js        = 1
replace_colors         = 1
overwrite_assets       = 0
always_enable_devtools = 1
current_theme          = Kanagawa
color_scheme           = Kanagawa
inject_css             = 1

[Preprocesses]
disable_sentry     = 1
disable_ui_logging = 1
remove_rtl_rule    = 1
expose_apis        = 1

; DO NOT CHANGE!
[Backup]
version = 1.2.98.301.gfcaeba72
with    = 2.44.0
