[[manager.prepend_keymap]]
on  = "cz"
run = 'shell --confirm "7z a \"%*\".zip %*"'
desc = "Compress selected to zip"

[[manager.prepend_keymap]]
on  = "e"
run = 'shell --orphan "explorer ."'
desc = "Open current directory in File Explorer"
