[[manager.prepend_keymap]]
on  = "cz"
run = 'shell --confirm "7z a \"%*\".zip %*"'
desc = "Compress selected to zip"

[[manager.prepend_keymap]]
on  = "e"
run = 'shell --orphan "explorer ."'
desc = "Open current directory in File Explorer"

[[manager.prepend_keymap]]
on  = "gw"
run = 'shell --confirm "echo hello"'
desc = "Open new terminal tab in current directory"
